---
# tasks to be run on all nodes
- name: Update package cache if older than 18000sec
  apt: update_cache=yes cache_valid_time=18000

- name: Install system packages
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - python-dev
    - python-setuptools
    - python-pip
    - authbind
    - supervisor
    - git
    - gcc
    - ntp
    - wget
    - curl
    - unzip

- name: Ensure pip is up-to-date
  command: pip install --upgrade pip

- name: Install Python packages
  pip: name={{ item }}
  with_items: 
    - virtualenv
    - virtualenvwrapper

- name: Allow app to bind to port 80
  file: path=/etc/authbind/byport/80 state=touch
        owner={{ APP_USER }} group={{ APP_USER }} mode=755

- name: Link to app-specific supervisor configuration
  file: >
    src={{ APP_DIR }}/supervisord.conf
    dest=/etc/supervisor/conf.d/{{ APP_NAME }}.conf
    state=link force=yes

- name: Start ntp service
  service: name=ntp enabled=yes state=started

##LETS ENCRYPT STUFF########################################
##: https://letsencrypt.readthedocs.org/en/latest/using.html
- name: Install letsencrypt pre-requisites
  apt: pkg={{ item }} state=present
  with_items:
    - swig

- name: git clone letsencrypt repo
  command: wget --directory-prefix=/tmp --no-clobber --continue https://github.com/letsencrypt/lets-encrypt-preview/archive/master.zip chdir=/tmp

- name: unzip letsencrypt
  command: unzip -n /tmp/master.zip -d /tmp chdir=/tmp

- name: rm .zip files from /tmp
  command: sudo rm -rf *.zip* chdir=/tmp

- name: install letsencrypt client
  command: ./bootstrap/ubuntu.sh chdir=/tmp/lets-encrypt-preview-master

- name: install letsencrypt client requirements
  command: sudo pip install -r requirements.txt chdir=/tmp/lets-encrypt-preview-master


#usng the client:
#>> ./venv/bin/letsencrypt --help
#>> sudo letsencrypt -d www.example.org run --help
