---
APP_NAME: lets_encrypt_demo
APP_REPOSITORY: git@bitbucket.org:komuW/lets_encrypt_demo.git
APP_USER: "{{ ansible_ssh_user }}"
APP_HOME: "/home/{{ APP_USER }}"
APP_DIR: "{{ APP_HOME }}/{{ APP_NAME }}"
APP_VIRTUALENV: "{{ APP_HOME }}/.virtualenvs/{{ APP_NAME }}"
NGINX_PORT: 80
HTTPS_APP_PORT: 443
GUNICORN_PORT: 3000
SERVER_IP: 127.0.0.1

APP_STATIC_DIR: "{{ APP_DIR }}/static"

LETSENCRYPT_REPO: git@github.com:komuW/lets_encrypt_nginx_demo.git

APP_VERSION: dev